model_list:
  # OpenAI API models:
  # https://platform.openai.com/docs/models
  - model_name: gpt-4o
    litellm_params:
      model: gpt-4o
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: o1
    litellm_params:
      model: o1
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: o1-mini
    litellm_params:
      model: o1-mini
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: o3-mini
    litellm_params:
      model: o3-mini
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: o1-preview
    litellm_params:
      model: o1-preview
      api_key: "os.environ/OPENAI_API_KEY"
  # Anthropic (Claude) API models:
  # https://docs.anthropic.com/en/docs/about-claude/models#model-names
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: claude-3-5-sonnet-20240620
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-3-opus
    litellm_params:
      model: claude-3-opus-20240229
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-3-sonnet
    litellm_params:
      model: claude-3-sonnet-20240229
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-3-haiku
    litellm_params:
      model: claude-3-haiku-20240307
      api_key: "os.environ/ANTHROPIC_API_KEY"
