# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "sdbus" = super.buildPythonPackage rec {
    pname = "sdbus";
    version = "0.11.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/61/72/42e3018d33e4ca73186c0f0590c448b709348f0cc39a97f01ca556bb3e0b/sdbus-0.11.0.tar.gz";
      sha256 = "1l4i9fi7955w9wddznf5csfjd1ghv8lxq9rgxi0n9sjgwpdblvzq";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sdbus-networkmanager" = super.buildPythonPackage rec {
    pname = "sdbus-networkmanager";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/04/0c/6a67ebd967f3816022d04ab93db5f3d998a55d79c138af11feb1f59a6f10/sdbus_networkmanager-2.0.0-py3-none-any.whl";
      sha256 = "13xhj6r91r907anmvak3mc9hn8fndakkq0lhr4b709n3n77mq2ki";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."sdbus"
    ];
  };
  "sdbus-notifications" = super.buildPythonPackage rec {
    pname = "sdbus-notifications";
    version = "1.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4c/36/aa04fdb0a50660304a7f7c6f0a4a9540daa4bd66832f79ebd610e75264be/sdbus_notifications-1.0.1-py3-none-any.whl";
      sha256 = "1nx291z5f3w4wffbs25sxzadn2dqfhfnvp6drgg8ylg3b9n461z4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."sdbus"
    ];
  };
}
