vscode_version = "1.88.0"

[[extensions]]
publisher_name = "ms-vscode-remote"
extension_name = "remote-ssh"

[[extensions]]
publisher_name = "ms-python"
extension_name = "python"

[[extensions]]
publisher_name = "ms-python"
extension_name = "isort"

[[extensions]]
publisher_name = "ms-python"
extension_name = "vscode-pylance"

[[extensions]]
publisher_name = "dbaeumer"
extension_name = "vscode-eslint"

[[extensions]]
publisher_name = "esbenp"
extension_name = "prettier-vscode"

[[extensions]]
publisher_name = "jnoortheen"
extension_name = "nix-ide"

[[extensions]]
publisher_name = "arrterian"
extension_name = "nix-env-selector"

[[extensions]]
publisher_name = "sanaajani"
extension_name = "taskrunnercode"

[[extensions]]
publisher_name = "ms-vsliveshare"
extension_name = "vsliveshare"

# https://github.com/nix-community/nix4vscode/issues/54
#[[extensions]]
#publisher_name = "redhat"
#extension_name = "vscode-yaml"

[[extensions]]
publisher_name = "dracula-theme"
extension_name = "theme-dracula"

[[extensions]]
publisher_name = "coolbear"
extension_name = "systemd-unit-file"

[[extensions]]
publisher_name = "tamasfe"
extension_name = "even-better-toml"

[[extensions]]
publisher_name = "vscode-org-mode"
extension_name = "org-mode"

[[extensions]]
publisher_name = "Rubymaniac"
extension_name = "vscode-direnv"

[[extensions]]
publisher_name = "ms-toolsai"
extension_name = "jupyter"

[[extensions]]
publisher_name = "Gleam"
extension_name = "gleam"

[[extensions]]
publisher_name = "JakeBecker"
extension_name = "elixir-ls"

[[extensions]]
publisher_name = "GitHub"
extension_name = "vscode-github-actions"

[[extensions]]
publisher_name = "W4RH4WK"
extension_name = "souffle-syntax"

[[extensions]]
publisher_name = "jq-syntax-highlighting"
extension_name = "jq-syntax-highlighting"

[[extensions]]
publisher_name = "denoland"
extension_name = "vscode-deno"

[[extensions]]
publisher_name = "James-Yu"
extension_name = "latex-workshop"

[[extensions]]
publisher_name = "dracula-theme"
extension_name = "theme-dracula"

#[[extensions]]
#publisher_name = "eamodio"
#extension_name = "gitlens"